/** ACTION TYPES FOR OVERLAY LOADING */
export const START_OVERLAY_LOADING = "START_OVERLAY_LOADING";
export const STOP_OVERLAY_LOADING = "STOP_OVERLAY_LOADING";



/** ACTION TYPES FOR AUTH */
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";


/** ACTION TYPES FOR HOME */
export const GET_PLACES = "GET_PLACES";
export const GET_ALL_CITY="GET_ALL_CITY";
export const LOGOUT = "LOGOUT"


//TODO SEARCH MODULE
export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";


export const LOADER_SET = 'loader/SET'
